### PR TITLE
Add slides from Chris Roper's presentation at OK Lab Berlin

### PR DESCRIPTION
**Pull request by k-nut**
As discussed in Slack: I'm adding the slides to the repo as a workaround for static file hosting so that we can share a link with others.

### CODE REVIEW

**Review by ubergesundheit — APPROVED** [review]

**Comment by ubergesundheit** [comment]
Quick Idea: Add a README file to the `content/ressourcen` directory to explain what it's purpose is. (Static asset hosting)

**Comment by michael-k** [comment]
Everyone who clones this repository also has to download this PDF and store it on disk.  This doesn't sound reasonably to me.

Why not create a dedicated repository for this?  Links to GitHub can also be used to share files. ([example](https://raw.githubusercontent.com/okfde/codefor.de/ok-lab-berlin-codeforafrica-slides/content/ressourcen/CfAFRICA%20|%20Presentation%20|%20for%20Code%20for%20Berlin.pdf))  In addition the contents of such a repository could be made available via subdomain of codefor.de.

Also git lfs (supported by GitHub) and git annex are way better suited for large files.

**Comment by k-nut** [comment]
I totally agree that this is not the "correct" solution to do this. 

I wonder if @robbi5 or @greg0r have opinions on how to do this as the system which hosts the website in the end would also need to support git lfs. Maybe something completely separate like static.codefor.de would be easier to set up?

**Comment by k-nut** [comment]
We now created a [dedicated repository](https://github.com/codeforberlin/files) for this as a workaround. Closing the PR here.

**Pull request closed without merging**
