### PR TITLE
add global license

### PR DESCRIPTION
**Pull request by ubergesundheit**

### CODE REVIEW

**Comment by robbi5** [comment]
for the old website we've had also a cc-license for the contents/texts. can we add this in this pr too?

**Comment by k-nut** [comment]
@ubergesundheit are you also going to add the CC-BY note to the bottom of the page and to the readme again? If so, I'd say this looks good to me!

**Comment by k-nut** [comment]
@ubergesundheit this PR is currently made out to the `dev` branch. Can you change it to `main`?

**Review by k-nut — APPROVED** [review]
LGTM! 👍

**Pull request merged**
