### PR TITLE
No more jquery

### PR DESCRIPTION
**Pull request by ubergesundheit**
This PR aims to remove or replace jquery and do some other general cleanup.

- [x] Remove jquery from map page
- [x] Update leaflet & simplify map page generation code  
- [x] Remove javascript based collapsibles and replace with html native `<details>` implementation
- [x] Remove unused files
- [x] Fix markdown syntax of gendered words on some pages
- [x] Remove js based "load more" button on blog and replace with pager
- [x] Some wording changes in some texts 
- [x] Get rid of bootstrap, popper, jquery files 
  - Mobile menu and mitmachen dropdown still use this

### CODE REVIEW

**Comment by digital-codes** [comment]
Habe alles angeschaut. Auf der Lab Berlin Seite gibt's einen Overflow bei OParl in der 1280 Ansicht in Percy. Das sollte noch weg. SOnst habe ich nichts gefunden. Für die fehlenden Anker auf "Ziele" habe ich schon einen Issue https://github.com/okfde/codefor.de/issues/233  aufgemacht. Falls Du das gleich noch mit machen willst ....

**Comment by digital-codes** [comment]
OK, the anchor issue seemst to be an artefact. The "Oparl overflow" has been there before, so not related to thsi PR. Thing is, I don't know how to review + approve in percy which still errors and without I cannot approve this PR.

**Comment by ubergesundheit** [comment]
@digital-codes please don't click "update branch" for someone elses Pull Requests. Thanks!

**Review by k-nut — APPROVED** [review]
Nice, I think this is looking really good. Thank you for all the spring cleaning work! 🧹

**Pull request merged**
