### PR TITLE
update urls

### PR DESCRIPTION
**Pull request by ricki-z**

### CODE REVIEW

**Review by ubergesundheit — COMMENTED** [review]
The image file seems empty?

**Comment by ricki-z** [comment]
> The image file seems empty?

In the preview it's shown: https://deploy-preview-235--hungry-heisenberg-4bd67f.netlify.app/projekte/stgt-dust-sensor/

**Review by ubergesundheit — APPROVED** [review]
looks good

**Comment by ubergesundheit** [comment]
Oops looks like we forgot to merge :P 

Can you rebase your branch against the current main or enable "allow maintainers to modify branch" ?

**Pull request merged**
