### PR TITLE
Unify spelling.

### PR DESCRIPTION
**Pull request by johnjohndoe**
- Open Data resp. Open-Data-...
- Open Source

### CODE REVIEW

**Comment by k-nut** [comment]
I would argue that we usually spell it `Open Data`, no?

**Comment by sonjafischbauer** [comment]
yes, we spell it Open Data and Open Source

**Comment by johnjohndoe** [comment]
:heavy_check_mark: Changed.

**Review by k-nut — APPROVED** [review]

**Comment by k-nut** [comment]
Thank you @johnjohndoe 🙏

**Pull request merged**
